### ISSUE TITLE
Focus States missing for btn-link class

### ISSUE THREAD

**Issue by derick-montague** [gtmills/phosphor-webui-vue#59]
## Tasks
1. Create a bootstrap overrides scss file
2. Add a focus state that will match the focus state for links

## Overview
The reason for adding the overrides is to be able to not tightly couple any overrides with global or scoped styles. This will allow for any overrides to be easily tested and removed if/when Bootstrap is updated in the future. I submitted an [issue in the bootstrap repo](https://github.com/twbs/bootstrap/issues/29891).

**Comment by yoshiemuranaka** [comment]
I noticed this issue when working on styling the primary navigation. The focus state doesn't have a box-shadow, but the text is underlined like a link would be. I wonder if this was intentional to keep it styled like a link? 
Regardless, I agree we should add a box shadow to this variant...my thought was that we should use the link variant as we were using the tertiary button style in Angular

**Comment by derick-montague** [comment]
>  I wonder if this was intentional to keep it styled like a link?

I hope not since even links should have a focus state, which is typically the blue outline.

> Regardless, I agree we should add a box shadow to this variant...my thought was that we should use the link variant as we were using the tertiary button style in Angular

That sounds good.

**Comment by derick-montague** [comment]
Moved to IBM tracking repo
